package Interfaces.SesionCliente;

import Clases.Usuario.Cliente;
import Interfaces.SesionCliente.BuscarEvento;
import Interfaces.SesionAdmin.ConsultarReservas;
import Interfaces.SesionAdmin.ConsultarReservas;
import Interfaces.VentanaPrincipal.JavaEvents;
import Interfaces.VentanaPrincipal.JavaEvents;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sergio
 */
public class Clientes extends javax.swing.JFrame {
    private Cliente clienteEncontrado;
    /**
     * Creates new form Cliente
     */
    public Clientes(Cliente client) {        
        initComponents();
        this.clienteEncontrado = client;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PerfilBoton = new javax.swing.JButton();
        BuscarEventoBoton = new javax.swing.JButton();
        Correotxt = new javax.swing.JLabel();
        ReservarEventosBoton = new javax.swing.JButton();
        ReseñasEventosBoton = new javax.swing.JButton();
        ConsultaReservasBoton = new javax.swing.JButton();
        JavaEventsLabel = new javax.swing.JLabel();
        SeparadorArriba = new javax.swing.JSeparator();
        SeparadorAbajo = new javax.swing.JSeparator();
        BienvenidoLabel = new javax.swing.JLabel();
        SeleccioneLabel = new javax.swing.JLabel();
        ComenzarLabel = new javax.swing.JLabel();
        QuererSalirTexto = new javax.swing.JLabel();
        HomeBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PerfilBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man (1).png"))); // NOI18N
        PerfilBoton.setBorderPainted(false);
        PerfilBoton.setContentAreaFilled(false);
        PerfilBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBotonActionPerformed(evt);
            }
        });

        BuscarEventoBoton.setBackground(new java.awt.Color(204, 204, 204));
        BuscarEventoBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        BuscarEventoBoton.setText("Buscar Evento");
        BuscarEventoBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BuscarEventoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEventoBotonActionPerformed(evt);
            }
        });

        Correotxt.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        Correotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correotxt.setText("Perfil Cliente");

        ReservarEventosBoton.setBackground(new java.awt.Color(204, 204, 204));
        ReservarEventosBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        ReservarEventosBoton.setText("Reservar Eventos");
        ReservarEventosBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ReservarEventosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarEventosBotonActionPerformed(evt);
            }
        });

        ReseñasEventosBoton.setBackground(new java.awt.Color(204, 204, 204));
        ReseñasEventosBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        ReseñasEventosBoton.setText("Reseñas Eventos");
        ReseñasEventosBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ReseñasEventosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReseñasEventosBotonActionPerformed(evt);
            }
        });

        ConsultaReservasBoton.setBackground(new java.awt.Color(204, 204, 204));
        ConsultaReservasBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        ConsultaReservasBoton.setText("Consultar Reservas");
        ConsultaReservasBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ConsultaReservasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaReservasBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PerfilBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Correotxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BuscarEventoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ReservarEventosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ReseñasEventosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConsultaReservasBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PerfilBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Correotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuscarEventoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReservarEventosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReseñasEventosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ConsultaReservasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        JavaEventsLabel.setFont(new java.awt.Font("Reem Kufi", 1, 36)); // NOI18N
        JavaEventsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEventsLabel.setText("JAVA EVENTS");
        jPanel1.add(JavaEventsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 370, 100));

        SeparadorArriba.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SeparadorArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 370, 50));

        SeparadorAbajo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SeparadorAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 370, 80));

        BienvenidoLabel.setBackground(new java.awt.Color(0, 0, 0));
        BienvenidoLabel.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        BienvenidoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidoLabel.setText("BIENVENIDO AL MENU DEL CLIENTE,");
        jPanel1.add(BienvenidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 340, 70));

        SeleccioneLabel.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        SeleccioneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeleccioneLabel.setText("SELECCIONE UNO DE LOS 4 BOTONES");
        jPanel1.add(SeleccioneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 360, 70));

        ComenzarLabel.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        ComenzarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComenzarLabel.setText("PARA COMENZAR A OPERAR");
        jPanel1.add(ComenzarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 360, 90));

        QuererSalirTexto.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        QuererSalirTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuererSalirTexto.setText("SI QUIERE SALIR PULSE EL BOTON HOME");
        jPanel1.add(QuererSalirTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 370, 90));

        HomeBoton.setBackground(new java.awt.Color(102, 102, 102));
        HomeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (3).png"))); // NOI18N
        HomeBoton.setBorderPainted(false);
        HomeBoton.setContentAreaFilled(false);
        HomeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBotonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 90, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarEventoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEventoBotonActionPerformed
        
        //Pasar a ventana de BuscarEvento 
        
        BuscarEvento frame3 = new BuscarEvento();
        frame3.setVisible(true);
        dispose();
    }//GEN-LAST:event_BuscarEventoBotonActionPerformed

    private void ReservarEventosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarEventosBotonActionPerformed
        
        //Pasar a ventana de ReservarEventos
        
        BuscarEvento frame4 = new BuscarEvento();
        frame4.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReservarEventosBotonActionPerformed

    private void ReseñasEventosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReseñasEventosBotonActionPerformed
        
        //Pasar a ventana de ReseñasEventos
        
        ReseñasEventos frame2 = new ReseñasEventos();
        frame2.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReseñasEventosBotonActionPerformed

    private void ConsultaReservasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaReservasBotonActionPerformed
        
        //Pasar a ventana de ConsultarReservas
        
        ConsultarReservas frame5 = new ConsultarReservas();
        frame5.setVisible(true);
        dispose();
    }//GEN-LAST:event_ConsultaReservasBotonActionPerformed

    private void PerfilBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBotonActionPerformed
        
        //Pasar a ventana de ModificarPerfil
        
        Modificarperfil frame6 = new Modificarperfil(clienteEncontrado);
        frame6.setVisible(true);
        dispose();
    }//GEN-LAST:event_PerfilBotonActionPerformed

    private void HomeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBotonActionPerformed
        
        //Pasar a ventana de JavaEvents
        
        JavaEvents frame1 = new JavaEvents(clienteEncontrado);
        frame1.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidoLabel;
    private javax.swing.JButton BuscarEventoBoton;
    private javax.swing.JLabel ComenzarLabel;
    private javax.swing.JButton ConsultaReservasBoton;
    private javax.swing.JLabel Correotxt;
    private javax.swing.JButton HomeBoton;
    private javax.swing.JLabel JavaEventsLabel;
    private javax.swing.JButton PerfilBoton;
    private javax.swing.JLabel QuererSalirTexto;
    private javax.swing.JButton ReservarEventosBoton;
    private javax.swing.JButton ReseñasEventosBoton;
    private javax.swing.JLabel SeleccioneLabel;
    private javax.swing.JSeparator SeparadorAbajo;
    private javax.swing.JSeparator SeparadorArriba;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
