package Interfaces.SesionCliente;

import Clases.GuardadoDatos.UtilJavaEventsClientes;
import Clases.Usuario.Cliente;
import Interfaces.Logins.IniciodesesionCliente;
import Interfaces.SesionCliente.Clientes;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sergio
 */
public class Modificarperfil extends javax.swing.JFrame {
    private Cliente clienteEncontrado;
    /**
     * Creates new form Modificarperfil
     */
    public Modificarperfil(Cliente client) {
        initComponents();
        this.clienteEncontrado = client;
        cargarDatosTextField();
    }
        private void cargarDatosTextField() {
            
        Nombretxt.setText(clienteEncontrado.getNombre());
        Correotxt.setText(clienteEncontrado.getCorreo());
        Teléfonotxt.setText(clienteEncontrado.getTelefono());
        Clavetxt.setText(clienteEncontrado.getClave());
        calletxt.setText(clienteEncontrado.getDireccion().getCalle());
        numerotxt.setText(clienteEncontrado.getDireccion().getNumero());
        CodigoPostaltxt.setText(clienteEncontrado.getDireccion().getCodigopostal());
        Ciudadtxt.setText(clienteEncontrado.getDireccion().getCiudad());
        Titulartxt.setText(clienteEncontrado.getTarjetaDeCredito().getNombre());
        NumeroTarjetatxt.setText(clienteEncontrado.getTarjetaDeCredito().getNumero());
        FechaCaducidadtxt.setText(clienteEncontrado.getTarjetaDeCredito().getFechaCaducidad());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegresaryGuardarBoton = new javax.swing.JButton();
        CrearEventoLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        Direccion1 = new javax.swing.JLabel();
        Calle = new javax.swing.JLabel();
        calletxt = new javax.swing.JTextField();
        EjCalle = new javax.swing.JLabel();
        Numero1 = new javax.swing.JLabel();
        numerotxt = new javax.swing.JTextField();
        EjNumero = new javax.swing.JLabel();
        CodigoPostaltxt = new javax.swing.JTextField();
        CodigoPostal = new javax.swing.JLabel();
        EjCodigo = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Titulartxt = new javax.swing.JTextField();
        Ciudad1 = new javax.swing.JLabel();
        Ciudad = new javax.swing.JLabel();
        Ciudadtxt = new javax.swing.JTextField();
        Numero = new javax.swing.JLabel();
        EjCiudad = new javax.swing.JLabel();
        NumeroTarjetatxt = new javax.swing.JFormattedTextField();
        jSeparator5 = new javax.swing.JSeparator();
        FechaCaducidadtxt = new javax.swing.JTextField();
        Titulo2 = new javax.swing.JLabel();
        Nombretxt = new javax.swing.JTextField();
        Tipo1 = new javax.swing.JLabel();
        Correotxt = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Clavetxt = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        HomeBoton = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Teléfonotxt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresaryGuardarBoton.setBackground(new java.awt.Color(102, 102, 102));
        RegresaryGuardarBoton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        RegresaryGuardarBoton.setText("Regresar y Guardar");
        RegresaryGuardarBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegresaryGuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresaryGuardarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(RegresaryGuardarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        CrearEventoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CrearEventoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearEventoLabel.setText("MODIFICAR PERFIL");
        jPanel1.add(CrearEventoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 32));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 10));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 20, 430));

        Direccion1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Direccion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion1.setText("DIRECCION");
        jPanel1.add(Direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 320, 50));

        Calle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calle.setText("Calle:");
        jPanel1.add(Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, 40));

        calletxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(calletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, -1));

        EjCalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjCalle.setForeground(new java.awt.Color(153, 153, 153));
        EjCalle.setText("Ej:Bulevar Entrepeñas...");
        jPanel1.add(EjCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 120, 20));

        Numero1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Numero1.setText("Numero:");
        jPanel1.add(Numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 70, 40));

        numerotxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numerotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerotxtActionPerformed(evt);
            }
        });
        jPanel1.add(numerotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 110, -1));

        EjNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjNumero.setForeground(new java.awt.Color(153, 153, 153));
        EjNumero.setText("Ej: 8A, 4B, 2C...");
        jPanel1.add(EjNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 90, 20));

        CodigoPostaltxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(CodigoPostaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, -1));

        CodigoPostal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CodigoPostal.setText("Codigo Postal:");
        jPanel1.add(CodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 80, 20));

        EjCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjCodigo.setForeground(new java.awt.Color(153, 153, 153));
        EjCodigo.setText("Ej: 19005, 26007...");
        jPanel1.add(EjCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 100, 20));

        Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Titulo1.setText("Titular:");
        jPanel1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 110, 22));

        Titulartxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Titulartxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitulartxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TitulartxtMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitulartxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TitulartxtMouseReleased(evt);
            }
        });
        Titulartxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                TitulartxtComponentMoved(evt);
            }
        });
        Titulartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitulartxtActionPerformed(evt);
            }
        });
        jPanel1.add(Titulartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 180, -1));

        Ciudad1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ciudad1.setText("Ciudad:");
        jPanel1.add(Ciudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 70, 30));

        Ciudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ciudad.setText("Numero de la tarjeta:");
        jPanel1.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, 30));

        Ciudadtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(Ciudadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 110, -1));

        Numero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Numero.setText("Fecha de Caducidad:");
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 40));

        EjCiudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjCiudad.setForeground(new java.awt.Color(153, 153, 153));
        EjCiudad.setText("Ej: Madrid, Vigo...");
        jPanel1.add(EjCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 100, 20));

        try {
            NumeroTarjetatxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(NumeroTarjetatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 320, 20));

        FechaCaducidadtxt.setText("  /  ");
        jPanel1.add(FechaCaducidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, -1));

        Titulo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Titulo2.setText("Nombre:");
        jPanel1.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 22));

        Nombretxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nombretxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombretxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NombretxtMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombretxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NombretxtMouseReleased(evt);
            }
        });
        Nombretxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                NombretxtComponentMoved(evt);
            }
        });
        Nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretxtActionPerformed(evt);
            }
        });
        jPanel1.add(Nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        Tipo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tipo1.setText("Correo:");
        jPanel1.add(Tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 69, 40));

        Correotxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Correotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CorreotxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CorreotxtMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CorreotxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CorreotxtMouseReleased(evt);
            }
        });
        Correotxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                CorreotxtComponentMoved(evt);
            }
        });
        Correotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreotxtActionPerformed(evt);
            }
        });
        jPanel1.add(Correotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Titulo.setText("Telefono:");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 22));

        Tipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tipo.setText("Clave:");
        jPanel1.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 69, 40));

        Clavetxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Clavetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClavetxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClavetxtMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClavetxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClavetxtMouseReleased(evt);
            }
        });
        Clavetxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                ClavetxtComponentMoved(evt);
            }
        });
        Clavetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClavetxtActionPerformed(evt);
            }
        });
        jPanel1.add(Clavetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 180, -1));

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion.setText("TARJETA DE CRÉDITO");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 50));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergio\\OneDrive\\Documentos\\NetBeansProjects\\JavaEvents\\src\\main\\resources\\tarjetadecredito (4).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 340, 210));

        HomeBoton.setBackground(new java.awt.Color(102, 102, 102));
        HomeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (3).png"))); // NOI18N
        HomeBoton.setBorderPainted(false);
        HomeBoton.setContentAreaFilled(false);
        HomeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBotonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 50));

        Borrar.setBackground(new java.awt.Color(102, 102, 102));
        Borrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Borrar.setText("Borrar");
        Borrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 100, 20));

        try {
            Teléfonotxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(Teléfonotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegresaryGuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresaryGuardarBotonActionPerformed
        
        //Guardara todos los datos de nuevo en el archivo de clientes.dat actualizando aquellos datos que se hayan modificado
               
        clienteEncontrado.setNombre(Nombretxt.getText());
        clienteEncontrado.setCorreo(Correotxt.getText());
        clienteEncontrado.setClave(Clavetxt.getText());
        clienteEncontrado.setTelefono(Teléfonotxt.getText());
        clienteEncontrado.getDireccion().setCalle(calletxt.getText());
        clienteEncontrado.getDireccion().setNumero(numerotxt.getText());
        clienteEncontrado.getDireccion().setCodigopostal(CodigoPostaltxt.getText());
        clienteEncontrado.getDireccion().setCiudad(Ciudadtxt.getText());
        clienteEncontrado.getTarjetaDeCredito().setNombre(Titulartxt.getText());
        clienteEncontrado.getTarjetaDeCredito().setNumero(NumeroTarjetatxt.getText());
        clienteEncontrado.getTarjetaDeCredito().setFechaCaducidad(FechaCaducidadtxt.getText());
        UtilJavaEventsClientes.guardarDatosClientes();
        JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.");
    }//GEN-LAST:event_RegresaryGuardarBotonActionPerformed

    private void numerotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerotxtActionPerformed

    private void NombretxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombretxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtMouseClicked

    private void NombretxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombretxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtMouseEntered

    private void NombretxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombretxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtMousePressed

    private void NombretxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombretxtMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtMouseReleased

    private void NombretxtComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NombretxtComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtComponentMoved

    private void NombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtActionPerformed

    private void CorreotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreotxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreotxtMouseClicked

    private void CorreotxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreotxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreotxtMouseEntered

    private void CorreotxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreotxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreotxtMousePressed

    private void CorreotxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreotxtMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreotxtMouseReleased

    private void CorreotxtComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CorreotxtComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreotxtComponentMoved

    private void CorreotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreotxtActionPerformed

    private void ClavetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClavetxtMouseClicked

    }//GEN-LAST:event_ClavetxtMouseClicked

    private void ClavetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClavetxtMouseEntered

    }//GEN-LAST:event_ClavetxtMouseEntered

    private void ClavetxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClavetxtMousePressed

    }//GEN-LAST:event_ClavetxtMousePressed

    private void ClavetxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClavetxtMouseReleased
        
    }//GEN-LAST:event_ClavetxtMouseReleased

    private void ClavetxtComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ClavetxtComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ClavetxtComponentMoved

    private void ClavetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClavetxtActionPerformed

    }//GEN-LAST:event_ClavetxtActionPerformed

    private void TitulartxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitulartxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulartxtMouseClicked

    private void TitulartxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitulartxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulartxtMouseEntered

    private void TitulartxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitulartxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulartxtMousePressed

    private void TitulartxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitulartxtMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulartxtMouseReleased

    private void TitulartxtComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TitulartxtComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulartxtComponentMoved

    private void TitulartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitulartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulartxtActionPerformed

    private void HomeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBotonActionPerformed

        //Pasar a ventana de IniciodesesionCliente
        
        
        UtilJavaEventsClientes.guardarDatosClientes();
        Clientes frame1 = new Clientes(clienteEncontrado);
        frame1.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBotonActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed

        //Vaciara todos los campos si presiona este boton

        Nombretxt.setText("");
        Clavetxt.setText("");
        Correotxt.setText("");
        Teléfonotxt.setText("");
        Ciudadtxt.setText("");
        calletxt.setText("");
        numerotxt.setText("");
        CodigoPostaltxt.setText("");
        NumeroTarjetatxt.setText("");
        Titulartxt.setText("");
        FechaCaducidadtxt.setText("");
    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificarperfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificarperfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificarperfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificarperfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JLabel Calle;
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Ciudad1;
    private javax.swing.JTextField Ciudadtxt;
    private javax.swing.JTextField Clavetxt;
    private javax.swing.JLabel CodigoPostal;
    private javax.swing.JTextField CodigoPostaltxt;
    private javax.swing.JTextField Correotxt;
    private javax.swing.JLabel CrearEventoLabel;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Direccion1;
    private javax.swing.JLabel EjCalle;
    private javax.swing.JLabel EjCiudad;
    private javax.swing.JLabel EjCodigo;
    private javax.swing.JLabel EjNumero;
    private javax.swing.JTextField FechaCaducidadtxt;
    private javax.swing.JButton HomeBoton;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel Numero1;
    private javax.swing.JFormattedTextField NumeroTarjetatxt;
    private javax.swing.JButton RegresaryGuardarBoton;
    private javax.swing.JFormattedTextField Teléfonotxt;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JTextField Titulartxt;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JTextField calletxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField numerotxt;
    // End of variables declaration//GEN-END:variables
}
