package Interfaces.SesionCliente;

import Clases.Eventos.Direccion;
import Clases.Eventos.Evento;
import Clases.Eventos.Reserva;
import Clases.GuardadoDatos.UtilJavaEventsClientes;
import Clases.GuardadoDatos.UtilJavaEventsEventos;
import Clases.GuardadoDatos.UtilJavaEventsReservas;
import Clases.Usuario.Cliente;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sergio
 */
public class ReservarEventos extends javax.swing.JFrame {
    private Evento eventoSelected;
    private Cliente clienteEncontrado;
    /**
     * Creates new form ReservarEventos
     */
    public ReservarEventos(Evento eventoEncontrado, Cliente client) {
        initComponents();
        this.eventoSelected = eventoEncontrado;
        this.clienteEncontrado = client;
        cargarDatosTextField();
        
    }
    
        //Metodo que se encarga de colocar todos los datos de un evento que se han guardado en sus respectivas posiciones
    
        private void cargarDatosTextField() {
        Titulolabel.setText(eventoSelected.getTitulo());
        Tipolabel.setText(eventoSelected.getTipo());
        Callelabel.setText(eventoSelected.getDireccion().getCalle());
        Numerolabel.setText(eventoSelected.getDireccion().getNumero());
        Codigopostallabel.setText(eventoSelected.getDireccion().getCodigopostal());
        Ciudadlabel.setText(eventoSelected.getDireccion().getCiudad());
        Fechalabel.setText(eventoSelected.getFecha());
        Preciolabel1.setText(eventoSelected.getPrecio());
        Horalabel.setText(eventoSelected.getHora());
        RutaImagen.setText(eventoSelected.getPortada());
        String rutaImagen = eventoSelected.getPortada();
       
        
        //Esta parte es la que se encarga de mostrar la imagen de nuevo otra vez al JLabel
        
        if (rutaImagen != null && !rutaImagen.isEmpty()) { //Esta linea se encarga de verificar que la variable rutaImagen no sea nula o este vacia
            ImageIcon iconoOriginal = new ImageIcon(rutaImagen); //En esta linea se crea una variable con la ruta de la imagen que hemos guardado cuando creamos el evento
            Image imagenOriginal = iconoOriginal.getImage(); //Obtiene la imagen de la imagen original por asi decirlo
            Image imagenEscalada = imagenOriginal.getScaledInstance(310, 250, Image.SCALE_SMOOTH); //Escala la imagen segun el tamaño del label al que quieres redireccionar la imagen en nuestro caso el label es 310x250
            ImageIcon iconoEscalado = new ImageIcon(imagenEscalada); //Convierte la imagen que hemos puesto en el label en una nueva variable y adapta el tamaño que hemos seleccionado antes.
            IconoImagen.setIcon(iconoEscalado); //Muestra la imagen en el JLable que en nuestro caso se llama IconoImagen y asi el usuario puede ver la imagen
            } else {
            IconoImagen.setIcon(null); // Si no hay ruta, se encargara de limpia el JLabel y dejarlo vacio.
            }
    }
        
        
        private void cargarTextFieldImporte(){
        int numEntradas = Integer.parseInt(ComboBoxEntradas.getSelectedItem().toString());

        if (eventoSelected != null) {
            String precioS = String.valueOf(eventoSelected.getPrecio());
            int precio = (int) Math.round(Double.parseDouble(precioS));
        
            if (clienteEncontrado != null && clienteEncontrado.getvip()) {
                double importeConDescuento = precio * numEntradas * 0.9;
                String importeFinals = String.format("%.2f", importeConDescuento);
                Preciolabel1.setText(importeFinals);
                
            } else {
                double importe = precio * numEntradas;
                String importeFinalt = String.format("%.2f", importe);
                Preciolabel1.setText(importeFinalt);
            }
        }
        }

                
        
        
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RutaImagen = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        CrearEventoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Tipolabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Titulo = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Calle = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        CodigoPostal = new javax.swing.JLabel();
        Ciudad = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Precio = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        IconoImagen = new javax.swing.JLabel();
        Fechalabel = new javax.swing.JLabel();
        Titulolabel = new javax.swing.JLabel();
        Numerolabel = new javax.swing.JLabel();
        Codigopostallabel = new javax.swing.JLabel();
        Callelabel = new javax.swing.JLabel();
        Horalabel = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Ciudadlabel = new javax.swing.JLabel();
        HomeBoton = new javax.swing.JButton();
        ComboBoxEntradas = new javax.swing.JComboBox<>();
        CargarImporte = new javax.swing.JButton();
        Preciolabel1 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();

        RutaImagen.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearEventoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CrearEventoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearEventoLabel.setText("RESERVA DE EVENTOS");
        jPanel1.add(CrearEventoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 32));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 20, 430));

        Tipolabel.setForeground(new java.awt.Color(255, 255, 255));
        Tipolabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Tipolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 110, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 670, 10));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Titulo.setText("Titulo del Evento:");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 110, 22));

        Tipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tipo.setText("Tipo:");
        jPanel1.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 69, 40));

        Calle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calle.setText("Calle:");
        jPanel1.add(Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 80, 40));

        Numero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Numero.setText("Numero:");
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 70, 40));

        CodigoPostal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CodigoPostal.setText("Codigo Postal:");
        jPanel1.add(CodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 80, 20));

        Ciudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ciudad.setText("Ciudad:");
        jPanel1.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 70, 40));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 320, 20));

        Precio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Precio.setText("Precio:");
        jPanel1.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 69, 30));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Fecha.setText("Fecha:");
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 69, 22));

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Hora.setText("Hora");
        jPanel1.add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 110, 20));
        jPanel1.add(IconoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 310, 250));

        Fechalabel.setForeground(new java.awt.Color(255, 255, 255));
        Fechalabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Fechalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 110, 20));

        Titulolabel.setForeground(new java.awt.Color(255, 255, 255));
        Titulolabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Titulolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 110, 20));

        Numerolabel.setForeground(new java.awt.Color(255, 255, 255));
        Numerolabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Numerolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 110, 20));

        Codigopostallabel.setForeground(new java.awt.Color(255, 255, 255));
        Codigopostallabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Codigopostallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 110, 20));

        Callelabel.setForeground(new java.awt.Color(255, 255, 255));
        Callelabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Callelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 110, 20));

        Horalabel.setForeground(new java.awt.Color(255, 255, 255));
        Horalabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Horalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 110, 20));

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion.setText("INFO SOBRE EL EVENTO");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 320, 50));

        Ciudadlabel.setForeground(new java.awt.Color(255, 255, 255));
        Ciudadlabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Ciudadlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 110, 20));

        HomeBoton.setBackground(new java.awt.Color(102, 102, 102));
        HomeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (3).png"))); // NOI18N
        HomeBoton.setBorderPainted(false);
        HomeBoton.setContentAreaFilled(false);
        HomeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBotonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 50));

        ComboBoxEntradas.setBackground(new java.awt.Color(102, 102, 102));
        ComboBoxEntradas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxEntradas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        ComboBoxEntradas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ComboBoxEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEntradasActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 100, -1));

        CargarImporte.setBackground(new java.awt.Color(102, 102, 102));
        CargarImporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarImporte.setText("Cargar Importe");
        CargarImporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CargarImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarImporteActionPerformed(evt);
            }
        });
        jPanel1.add(CargarImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 120, -1));

        Preciolabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Preciolabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 110, 20));

        Guardar.setBackground(new java.awt.Color(102, 102, 102));
        Guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Guardar.setText("Guardar Reservar y generar factura");
        Guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBotonActionPerformed

        //Pasar a ventana de IniciodesesionCliente

        BuscarEvento frame1 = new BuscarEvento();
        frame1.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBotonActionPerformed

    private void ComboBoxEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEntradasActionPerformed

    }//GEN-LAST:event_ComboBoxEntradasActionPerformed

    private void CargarImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarImporteActionPerformed
         cargarTextFieldImporte();
    }//GEN-LAST:event_CargarImporteActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
               
        //Este es el metodo que se encargará de guardar el evento si no ocurre ninguna excepcion
        
       
                
                //Si no salta ninguna excepcion se procederia a atribuir los datos de cada campos con los del Constructor de la clase evento y direccion
                
                String Fecha = Fechalabel.getText();
                String Precio = Preciolabel1.getText();
                String CantidadEntr = ComboBoxEntradas.getSelectedItem().toString();                
                Reserva r1 = new Reserva(Fecha,eventoSelected, clienteEncontrado, CantidadEntr, Precio);
                //En esta parte si el Usuario creado cumple con todos los requisitos se le dará de alta y saldra el mensaje de Evento Dado 
                //de alta y si por casualidad ya hay un evento creado asi se comparara y saldra el mensaje de Error al Dar de Alta
                
                if (UtilJavaEventsReservas.AltaReserva(r1)) {
                JOptionPane.showMessageDialog(this, "Reserva realizada, enjoy it :).", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    UtilJavaEventsReservas.guardarDatosReservas();
                    UtilJavaEventsEventos.guardarDatosEventos();
                    UtilJavaEventsClientes.guardarDatosClientes();
            } else {
                JOptionPane.showMessageDialog(this, "Error al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calle;
    private javax.swing.JLabel Callelabel;
    private javax.swing.JButton CargarImporte;
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Ciudadlabel;
    private javax.swing.JLabel CodigoPostal;
    private javax.swing.JLabel Codigopostallabel;
    private javax.swing.JComboBox<String> ComboBoxEntradas;
    private javax.swing.JLabel CrearEventoLabel;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Fechalabel;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton HomeBoton;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Horalabel;
    private javax.swing.JLabel IconoImagen;
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel Numerolabel;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Preciolabel1;
    private javax.swing.JTextField RutaImagen;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Tipolabel;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulolabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
