package Interfaces.Logins;


import Clases.Usuario.Cliente;
import Interfaces.Registros.Registrar;
import Interfaces.VentanaPrincipal.JavaEvents;
import Interfaces.VentanaPrincipal.JavaEvents;
import Interfaces.VentanaPrincipal.JavaEvents;
import Interfaces.Registros.Registrar;
import Interfaces.Registros.Registrar;
import Interfaces.SesionCliente.Clientes;
import Clases.GuardadoDatos.UtilJavaEventsClientes;
import static Clases.GuardadoDatos.UtilJavaEventsClientes.cargarDatosClientes;
import static Clases.GuardadoDatos.UtilJavaEventsClientes.guardarDatosClientes;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sergio
 */
public class IniciodesesionCliente extends javax.swing.JFrame {
    private Cliente clienteEncontrado;
    /**
     * Creates new form Iniciodesesion
     */
    public IniciodesesionCliente(Cliente client) {
        UtilJavaEventsClientes.cargarDatosClientes();
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsuarioLabel = new javax.swing.JLabel();
        ContraseñaLabel = new javax.swing.JLabel();
        CajaDeTextoUsuario = new javax.swing.JTextField();
        CajaDeTextoContraseña = new javax.swing.JPasswordField();
        BotonIngresar = new javax.swing.JButton();
        IniciarSesion = new javax.swing.JLabel();
        SeparadorDerecho = new javax.swing.JSeparator();
        SeparadorIzquierdo = new javax.swing.JSeparator();
        HomeBoton = new javax.swing.JButton();
        RegistrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarioLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        UsuarioLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user (1).png"))); // NOI18N
        UsuarioLabel.setText("USUARIO:");
        jPanel1.add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 250, 30));

        ContraseñaLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ContraseñaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ContraseñaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/key (1).png"))); // NOI18N
        ContraseñaLabel.setText("CONTRASEÑA:");
        jPanel1.add(ContraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 260, 30));

        CajaDeTextoUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        CajaDeTextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaDeTextoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(CajaDeTextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 260, 30));

        CajaDeTextoContraseña.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel1.add(CajaDeTextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 260, 30));

        BotonIngresar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BotonIngresar.setText("INGRESAR");
        BotonIngresar.setBorder(new javax.swing.border.MatteBorder(null));
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 200, 40));

        IniciarSesion.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        IniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/access-control (1).png"))); // NOI18N
        IniciarSesion.setText("INICIA SESIÓN");
        IniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 330, 70));

        SeparadorDerecho.setBackground(new java.awt.Color(255, 255, 255));
        SeparadorDerecho.setForeground(new java.awt.Color(0, 0, 0));
        SeparadorDerecho.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(SeparadorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 80, 400));

        SeparadorIzquierdo.setBackground(new java.awt.Color(255, 255, 255));
        SeparadorIzquierdo.setForeground(new java.awt.Color(0, 0, 0));
        SeparadorIzquierdo.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(SeparadorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 80, 400));

        HomeBoton.setBackground(new java.awt.Color(102, 102, 102));
        HomeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (3).png"))); // NOI18N
        HomeBoton.setBorderPainted(false);
        HomeBoton.setContentAreaFilled(false);
        HomeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBotonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 30));

        RegistrarBoton.setBackground(new java.awt.Color(102, 102, 102));
        RegistrarBoton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        RegistrarBoton.setText("Registrate gratis aqui!!");
        RegistrarBoton.setBorderPainted(false);
        RegistrarBoton.setContentAreaFilled(false);
        RegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
            
        //Se encarga de verificar si a la hora de acceder a la aplicacion se han rellenado todos los campos correctamente
        //y si se han rellenado de forma correcta procedera a buscar si ese cliente está registrado si no lo esta o se ha equivocado
        //al introducir los datos saldra un panel de mensaje diciendo que o el correo o la contraseña y si esta registrado
        //saldra un Panel de mensaje diciendo que el inicio de sesion ha sido exitoso y se abrira la pestaña de clientes.
        
        String correo = CajaDeTextoUsuario.getText();
        String contrasena = new String(CajaDeTextoContraseña.getPassword());

        if (correo.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cliente clienteEncontrado = null;
        for (Cliente c : UtilJavaEventsClientes.clientes) {
            if (c.getCorreo().equalsIgnoreCase(correo) && c.getClave().equals(contrasena)) {
                clienteEncontrado = c;
                break;
            }
        }

        if (clienteEncontrado != null) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
            UtilJavaEventsClientes.guardarDatosClientes();
            Clientes frame1 = new Clientes(clienteEncontrado);  
            frame1.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_BotonIngresarActionPerformed
    }
    
    private void HomeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBotonActionPerformed
        
        //Pasar a ventana de JavaEvents
        
        JavaEvents frame2 = new JavaEvents(clienteEncontrado);
        frame2.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_HomeBotonActionPerformed

    private void RegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBotonActionPerformed
        
        //Pasar a ventana de Registrar
        
        Registrar frame3 = new Registrar();
        frame3.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegistrarBotonActionPerformed

    private void CajaDeTextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaDeTextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaDeTextoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JPasswordField CajaDeTextoContraseña;
    private javax.swing.JTextField CajaDeTextoUsuario;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JButton HomeBoton;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JButton RegistrarBoton;
    private javax.swing.JSeparator SeparadorDerecho;
    private javax.swing.JSeparator SeparadorIzquierdo;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
