package Interfaces.Logins;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Clases.GuardadoDatos.UtilJavaEventsEventos;
import Clases.Usuario.Cliente;
import Interfaces.VentanaPrincipal.JavaEvents;
import Interfaces.SesionAdmin.Administrador;
import Interfaces.SesionAdmin.Administrador;
import Interfaces.VentanaPrincipal.JavaEvents;
import Interfaces.VentanaPrincipal.JavaEvents;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class IniciodesesionAdministrador extends javax.swing.JFrame {
        private Cliente clienteEncontrado;
    /**
     * Creates new form IniciodesesionAdministrador
     */
    public IniciodesesionAdministrador() {      
        initComponents();
        UtilJavaEventsEventos.cargarDatosEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SeparadorDerecho = new javax.swing.JSeparator();
        HomeBoton = new javax.swing.JButton();
        AdministradorTxt = new javax.swing.JLabel();
        AdministradorIcono = new javax.swing.JLabel();
        CajaDeTextoCorreo = new javax.swing.JTextField();
        SeparadorIzquierdo = new javax.swing.JSeparator();
        CajadeTextoContraseña = new javax.swing.JPasswordField();
        IngresarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeparadorDerecho.setBackground(new java.awt.Color(255, 255, 255));
        SeparadorDerecho.setForeground(new java.awt.Color(0, 0, 0));
        SeparadorDerecho.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(SeparadorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, 400));

        HomeBoton.setBackground(new java.awt.Color(102, 102, 102));
        HomeBoton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        HomeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (3).png"))); // NOI18N
        HomeBoton.setBorderPainted(false);
        HomeBoton.setContentAreaFilled(false);
        HomeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBotonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 30));

        AdministradorTxt.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        AdministradorTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdministradorTxt.setText("ADMINISTRADOR");
        jPanel1.add(AdministradorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 210, 50));

        AdministradorIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrator (2).png"))); // NOI18N
        jPanel1.add(AdministradorIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 140, 130));

        CajaDeTextoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaDeTextoCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(CajaDeTextoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 270, 30));

        SeparadorIzquierdo.setForeground(new java.awt.Color(0, 0, 0));
        SeparadorIzquierdo.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(SeparadorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 400));

        CajadeTextoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajadeTextoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(CajadeTextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 270, 30));

        IngresarBoton.setBackground(new java.awt.Color(0, 255, 255));
        IngresarBoton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IngresarBoton.setText("INGRESAR");
        IngresarBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        IngresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(IngresarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBotonActionPerformed
        
        //Pasar a ventana de JavaEvents
        
        JavaEvents frame1 = new JavaEvents(clienteEncontrado);
        frame1.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBotonActionPerformed

    private void CajaDeTextoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaDeTextoCorreoActionPerformed

    }//GEN-LAST:event_CajaDeTextoCorreoActionPerformed

    private void IngresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBotonActionPerformed
        
        //Método para mostrar mensaje si los datos son incorrectos o para pasar a ventana de Administrador si son correctos 
        
        JFrame mensaje = new JFrame("Validacion de inicio de sesion");
        if(!CajaDeTextoCorreo.getText().trim().equals("admin@javaevents.com") || !CajadeTextoContraseña.getText().trim().equals("admin")) {
            JOptionPane.showMessageDialog(mensaje, "Las credenciales no son correctas");
            CajaDeTextoCorreo.setText("");
            CajadeTextoContraseña.setText("");
        }
        else {
            Administrador frame2 = new Administrador();
            frame2.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_IngresarBotonActionPerformed

    private void CajadeTextoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajadeTextoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajadeTextoContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciodesesionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciodesesionAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministradorIcono;
    private javax.swing.JLabel AdministradorTxt;
    private javax.swing.JTextField CajaDeTextoCorreo;
    private javax.swing.JPasswordField CajadeTextoContraseña;
    private javax.swing.JButton HomeBoton;
    private javax.swing.JButton IngresarBoton;
    private javax.swing.JSeparator SeparadorDerecho;
    private javax.swing.JSeparator SeparadorIzquierdo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
