/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces.VentanaPrincipal;

import Clases.GuardadoDatos.UtilJavaEventsClientes;
import Clases.GuardadoDatos.UtilJavaEventsEventos;
import Clases.GuardadoDatos.UtilJavaEventsReservas;
import Clases.Usuario.Cliente;

/**
 *
 * @author Sergio
 */
public class Bienvenida extends javax.swing.JFrame {
    private Cliente clienteEncontrado;
    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        
        UtilJavaEventsClientes.cargarDatosClientes(); //Carga los Datos del archivo de clientes
        UtilJavaEventsEventos.cargarDatosEventos(); //Carga los Datos del archivo de eventos
        UtilJavaEventsReservas.cargarDatosReservas(); //Carga los Datos del archivo reservas.dat
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BIENVENIDO = new javax.swing.JLabel();
        JavaEventsLabel1 = new javax.swing.JLabel();
        Comenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BIENVENIDO.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        BIENVENIDO.setForeground(new java.awt.Color(255, 255, 255));
        BIENVENIDO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BIENVENIDO.setText("BIENVENIDO A");
        jPanel1.add(BIENVENIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 90));

        JavaEventsLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        JavaEventsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        JavaEventsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEventsLabel1.setText("JAVA EVENTS");
        jPanel1.add(JavaEventsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 90));

        Comenzar.setBackground(new java.awt.Color(102, 102, 102));
        Comenzar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Comenzar.setForeground(new java.awt.Color(255, 255, 255));
        Comenzar.setText("COMENZAR");
        Comenzar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(Comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarActionPerformed
        
        //Pasa a la ventana de JavaEvents 
        
        
        JavaEvents frame1 = new JavaEvents(clienteEncontrado);
        frame1.setVisible(true);
        
        //Cierra la ventana que está abierta
        dispose();
    }//GEN-LAST:event_ComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BIENVENIDO;
    private javax.swing.JButton Comenzar;
    private javax.swing.JLabel JavaEventsLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
