package Interfaces.SesionAdmin;

import Clases.Usuario.Cliente;
import Interfaces.VentanaPrincipal.JavaEvents;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sergio
 */
public class Administrador extends javax.swing.JFrame {
    private Cliente clienteEncontrado;
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        GestionEventosBoton = new javax.swing.JButton();
        ConsultaEventosBoton = new javax.swing.JButton();
        ConsultaUsuariosBoton = new javax.swing.JButton();
        ConsultaReservasBoton = new javax.swing.JButton();
        Correotxt = new javax.swing.JLabel();
        Foto = new javax.swing.JLabel();
        BienvenidoLabel = new javax.swing.JLabel();
        JavaEventsLabel = new javax.swing.JLabel();
        SeleccioneLabel = new javax.swing.JLabel();
        ComenzarLabel = new javax.swing.JLabel();
        SeparadorArriba = new javax.swing.JSeparator();
        SeparadorAbajo = new javax.swing.JSeparator();
        QuererSalirTexto = new javax.swing.JLabel();
        HomeBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GestionEventosBoton.setBackground(new java.awt.Color(204, 204, 204));
        GestionEventosBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        GestionEventosBoton.setText("Gestionar Evento");
        GestionEventosBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        GestionEventosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionEventosBotonActionPerformed(evt);
            }
        });

        ConsultaEventosBoton.setBackground(new java.awt.Color(204, 204, 204));
        ConsultaEventosBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        ConsultaEventosBoton.setText("Consultar Eventos");
        ConsultaEventosBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ConsultaEventosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaEventosBotonActionPerformed(evt);
            }
        });

        ConsultaUsuariosBoton.setBackground(new java.awt.Color(204, 204, 204));
        ConsultaUsuariosBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        ConsultaUsuariosBoton.setText("Consultar Usuarios");
        ConsultaUsuariosBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ConsultaUsuariosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaUsuariosBotonActionPerformed(evt);
            }
        });

        ConsultaReservasBoton.setBackground(new java.awt.Color(204, 204, 204));
        ConsultaReservasBoton.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        ConsultaReservasBoton.setText("Consultar Reservas");
        ConsultaReservasBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ConsultaReservasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaReservasBotonActionPerformed(evt);
            }
        });

        Correotxt.setFont(new java.awt.Font("Reem Kufi", 1, 12)); // NOI18N
        Correotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correotxt.setText("admin@javaevents.com");

        Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gentleman (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultaEventosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConsultaUsuariosBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConsultaReservasBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Correotxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(GestionEventosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Correotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GestionEventosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConsultaEventosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConsultaUsuariosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConsultaReservasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 400));

        BienvenidoLabel.setBackground(new java.awt.Color(0, 0, 0));
        BienvenidoLabel.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        BienvenidoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidoLabel.setText("BIENVENIDO AL MENU ADMINISTRADOR,");
        BienvenidoLabel.setAlignmentX(0.5F);
        jPanel1.add(BienvenidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 340, 70));

        JavaEventsLabel.setFont(new java.awt.Font("Reem Kufi", 1, 36)); // NOI18N
        JavaEventsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEventsLabel.setText("JAVA EVENTS");
        jPanel1.add(JavaEventsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 370, 100));

        SeleccioneLabel.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        SeleccioneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeleccioneLabel.setText("SELECCIONE UNO DE LOS 4 BOTONES");
        jPanel1.add(SeleccioneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 350, 70));

        ComenzarLabel.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        ComenzarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComenzarLabel.setText("PARA COMENZAR A OPERAR");
        jPanel1.add(ComenzarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 360, 90));

        SeparadorArriba.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SeparadorArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 370, 50));

        SeparadorAbajo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SeparadorAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 370, 80));

        QuererSalirTexto.setFont(new java.awt.Font("Reem Kufi", 1, 16)); // NOI18N
        QuererSalirTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuererSalirTexto.setText("SI QUIERE SALIR PULSE EL BOTON HOME");
        jPanel1.add(QuererSalirTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 370, 90));

        HomeBoton.setBackground(new java.awt.Color(102, 102, 102));
        HomeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (3).png"))); // NOI18N
        HomeBoton.setBorderPainted(false);
        HomeBoton.setContentAreaFilled(false);
        HomeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBotonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 90, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBotonActionPerformed
        
        //Pasar a la ventana de JavaEvents
        
        JavaEvents frame1 = new JavaEvents(clienteEncontrado);
        frame1.setVisible(true);
        
        //Cierra la ventana que esta abierta
        
        
        dispose();
    }//GEN-LAST:event_HomeBotonActionPerformed

    private void ConsultaUsuariosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuariosBotonActionPerformed
        
        //Pasar a la ventana de ConsultarUsuarios
        
        ConsultarUsuarios frame2 = new ConsultarUsuarios();
        frame2.setVisible(true);
        
        //Cierra la ventana que esta abierta
        
        
        dispose();
    }//GEN-LAST:event_ConsultaUsuariosBotonActionPerformed

    private void GestionEventosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionEventosBotonActionPerformed
        
        //Pasar a la ventana de GestionEventos
        
        GestionEventos frame3 = new GestionEventos();
        frame3.setVisible(true);
        
        //Cierra la ventana que esta abierta
        
        
        dispose();
    }//GEN-LAST:event_GestionEventosBotonActionPerformed

    private void ConsultaEventosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaEventosBotonActionPerformed
       
       //Pasar a la ventana de ConsultarEventos
        
       ConsultarEventos frame4 = new ConsultarEventos();
       frame4.setVisible(true);
       
       //Cierra la ventana que esta abierta
       
       
       dispose();
    }//GEN-LAST:event_ConsultaEventosBotonActionPerformed

    private void ConsultaReservasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaReservasBotonActionPerformed
        
        //Pasar a la ventana de ConsultarReservas
        
        ConsultarReservas frame5 = new ConsultarReservas();
        frame5.setVisible(true);
        
        //Cierra la ventana que esta abierta
        
        
        dispose();
    }//GEN-LAST:event_ConsultaReservasBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidoLabel;
    private javax.swing.JLabel ComenzarLabel;
    private javax.swing.JButton ConsultaEventosBoton;
    private javax.swing.JButton ConsultaReservasBoton;
    private javax.swing.JButton ConsultaUsuariosBoton;
    private javax.swing.JLabel Correotxt;
    private javax.swing.JLabel Foto;
    private javax.swing.JButton GestionEventosBoton;
    private javax.swing.JButton HomeBoton;
    private javax.swing.JLabel JavaEventsLabel;
    private javax.swing.JLabel QuererSalirTexto;
    private javax.swing.JLabel SeleccioneLabel;
    private javax.swing.JSeparator SeparadorAbajo;
    private javax.swing.JSeparator SeparadorArriba;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
