package Interfaces.SesionAdmin;

import Clases.GuardadoDatos.UtilJavaEventsClientes;
import Clases.GuardadoDatos.UtilJavaEventsEventos;
import Clases.Usuario.Cliente;
import java.awt.Frame;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sergio
 */
public class ConsultarUsuarios extends javax.swing.JFrame {
    private DefaultTableModel tabla = new DefaultTableModel(); //Crea una tabla la cual nos ayudara a realizar el filtrado de los clientes  
    ArrayList<Cliente> clientes = new ArrayList<>(); //Inicializa la ArrayList de clientes que tenemos creada en la clase UtilJavaEventsClientes donde tenemos guardados todos los datos de los eventos

    /**
     * Creates new form ConsultarUsuarios
     */
    public ConsultarUsuarios() {
        initComponents();  
        String columnas[] = {"Nombre", "Correo", "Clave", "Telefono", "Calle", "Numero", "Ciudad", "CodigoPostal", "Vip"}; //Crea una variable String llamada columnas que es la que nos permite organizar como apareceran los datos en la tabla creada anteriormente.
        tabla.setColumnIdentifiers(columnas); //Establece al modelo de tabla creado antes como se organizaran las diferentes columnas creadas.
        Tabla.setModel(tabla); //Establece el modelo de la tabla creada
        Tabla.getTableHeader().setReorderingAllowed(false); //Se encarga de que no se puedan mover las columnas ni descolocarlas, es decir, que no se puedan editar las columnas.
        ComboBoxFiltrar.setSelectedItem("Nombre"); //El ComboBox filtra como apareceran los clientes una vez entren a la ventana.  
        rellenaTabla("Nombre"); //La tabla se encarga de establecer el orden en el que se filtraran los clientes la primera vez que aparezcan los datos.
        this.setVisible(true);
    }
    
        //El Metodo rellenaTabla se va a encargar de permitir como poder rellenar la tabla como dice su nombre y la que va ayudar a 
        //que cuando se cargen los datos cada uno se coloque en la columna realizada anteriormente.
    
        public void rellenaTabla(String criterio) {
        limpiaTabla();
        if (criterio.equals("Nombre")) {
            clientes = UtilJavaEventsClientes.getClientesPorNombre();
        } else if (criterio.equals("Correo")) {
            clientes = UtilJavaEventsClientes.getClientesPorCorreo();
        }else if (criterio.equals("Contraseña")) {
            clientes = UtilJavaEventsClientes.getClientesPorClave();
        }else if (criterio.equals("Teléfono")) {
            clientes = UtilJavaEventsClientes.getClientesPorTelefono();
        }else if (criterio.equals("Calle")) {
            clientes = UtilJavaEventsClientes.getClientesPorCalle();
        }else if (criterio.equals("Número")) {
            clientes = UtilJavaEventsClientes.getClientesPorNumero();
        }else if (criterio.equals("Ciudad")) {
            clientes = UtilJavaEventsClientes.getClientesPorCiudad();
        }else if (criterio.equals("Codigo Postal")) {
            clientes = UtilJavaEventsClientes.getClientesPorCodigoPostal();
        }else if (criterio.equals("VIP")) {
            clientes = UtilJavaEventsClientes.getClientesPorVip();
        }      
        
        for (Cliente c : clientes) {
            tabla.addRow(new Object[]{c.getNombre(), c.getCorreo(), c.getClave(), c.getTelefono(), c.getDireccion().getCalle(), c.getDireccion().getNumero(), c.getDireccion().getCiudad(), c.getDireccion().getCodigopostal(), c.getvip()});
        }
    }
        
        //Metodo que se encarga de eliminar todas las filas de la tabla una vez se cierre y una vez se cargue esta ventana se 
        //colocaran los datos de nuevo a sus posiciones gracias al metodo rellenaTabla().
        
       public void limpiaTabla() {
        int filas = tabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            tabla.removeRow(0);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        ConsultaDeUsuarios = new javax.swing.JLabel();
        ScrollTabla = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        ActualizarMenu = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        QuitarVip = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        ComboBoxFiltrar = new javax.swing.JComboBox<>();
        FiltrarPor = new javax.swing.JLabel();
        DarVip = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConsultaDeUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ConsultaDeUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConsultaDeUsuarios.setText("CONSULTA DE USUARIOS");
        jPanel1.add(ConsultaDeUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        ScrollTabla.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollTabla.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Tabla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Contraseña", "Teléfono", "Calle", "Número", "Ciudad", "Codigo Postal", "Vip"
            }
        ));
        ScrollTabla.setViewportView(Tabla);

        jPanel1.add(ScrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 310));

        ActualizarMenu.setBackground(new java.awt.Color(255, 153, 255));
        ActualizarMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ActualizarMenu.setText("Actualizar Menú");
        ActualizarMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ActualizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, -1));

        Eliminar.setBackground(new java.awt.Color(255, 153, 255));
        Eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Eliminar.setText("Eliminar Usuario");
        Eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 120, -1));

        QuitarVip.setBackground(new java.awt.Color(255, 153, 255));
        QuitarVip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuitarVip.setText("Quitar Vip");
        QuitarVip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QuitarVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarVipActionPerformed(evt);
            }
        });
        jPanel1.add(QuitarVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 120, -1));

        BotonVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergio\\OneDrive\\Documentos\\NetBeansProjects\\JavaEvents\\src\\main\\resources\\left-arrow (1).png")); // NOI18N
        BotonVolver.setBorderPainted(false);
        BotonVolver.setContentAreaFilled(false);
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 50, 50));

        ComboBoxFiltrar.setBackground(new java.awt.Color(255, 153, 255));
        ComboBoxFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Correo", "Teléfono", "Código Postal", "VIP" }));
        ComboBoxFiltrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ComboBoxFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        FiltrarPor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltrarPor.setText("Filtrar por:");
        jPanel1.add(FiltrarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 90, 30));

        DarVip.setBackground(new java.awt.Color(255, 153, 255));
        DarVip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DarVip.setText("Dar Vip");
        DarVip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DarVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarVipActionPerformed(evt);
            }
        });
        jPanel1.add(DarVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarMenuActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        
        //Una vez se presione este boton si tiene seleccionada una fila/cliente
        //le saldra un panel de confirmacion con dos opciones SI o No si selecciona si el cliente se eliminara de la aplicacion
        //y guardara los datos en el archivo cliente seguido saldra un mensaje si todo ha salido bien con la nueva longitud del archivo clientes.dat
        
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
        JOptionPane.showMessageDialog(this, "No hay cliente seleccionado.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        return;
    }

        Cliente clienteAEliminar = clientes.get(fila);
        int decision = JOptionPane.YES_NO_OPTION;
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de que quiere eliminar este cliente?",
                    "Confirmación de acción", decision);



        if (respuesta != JOptionPane.YES_OPTION) {
        return;
    }
        // Eliminar de la lista
        clientes.remove(fila);
        // Guardar lista actualizada
        UtilJavaEventsClientes.guardarDatosClientes();
        JOptionPane.showMessageDialog(this, "Evento eliminado correctamente.");
        File archivo = new File("eventos.dat");
        System.out.println("Tamaño del archivo después de guardar: " + archivo.length());
       
    }//GEN-LAST:event_EliminarActionPerformed

    private void QuitarVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarVipActionPerformed
        
        //Este metodo se encarga de que una vez pulsando el boton y seleccionando el cliente se le quitara el Vip si lo tiene 
        //si no se selecciona nada saldra un Panel de mensaje diciendo que no hay un cliente seleccionado
        
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "No hay cliente seleccionado", "Mensjase", JOptionPane.ERROR_MESSAGE);
        } else {
            Cliente c1 = clientes.get(fila);
            c1.setvip(false);
            UtilJavaEventsClientes.guardarDatosClientes();
            JOptionPane.showMessageDialog(this, "El Cliente ya no es VIP.");
        }
    }//GEN-LAST:event_QuitarVipActionPerformed

    private void ComboBoxFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFiltrarActionPerformed
        String orden = (String) ComboBoxFiltrar.getSelectedItem();
        rellenaTabla(orden);

    }//GEN-LAST:event_ComboBoxFiltrarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        
        Administrador frame1 = new Administrador();
        frame1.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void DarVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarVipActionPerformed
        
        //Este metodo se encarga de que una vez pulsando el boton y seleccionando el cliente se le dara el Vip si no lo tiene 
        //si no se selecciona nada saldra un Panel de mensaje diciendo que no hay un cliente seleccionado
        
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "No hay cliente seleccionado.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        } else {
            Cliente c1 = clientes.get(fila);
            c1.setvip(true);
            UtilJavaEventsClientes.guardarDatosClientes();
            JOptionPane.showMessageDialog(this, "El Cliente ya es VIP.");
            
        }   
    }//GEN-LAST:event_DarVipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarMenu;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JComboBox<String> ComboBoxFiltrar;
    private javax.swing.JLabel ConsultaDeUsuarios;
    private javax.swing.JButton DarVip;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel FiltrarPor;
    private javax.swing.JButton QuitarVip;
    private javax.swing.JScrollPane ScrollTabla;
    private javax.swing.JTable Tabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
