package Interfaces.SesionAdmin;


import Interfaces.SesionAdmin.Administrador;
import Interfaces.SesionAdmin.Administrador;
import Interfaces.SesionAdmin.Administrador;
import Interfaces.SesionAdmin.CrearEvento;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sergio
 */
public class GestionEventos extends javax.swing.JFrame {

    /**
     * Creates new form GestionarEventos
     */
    public GestionEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tendrastxt = new javax.swing.JLabel();
        tendrastxt1 = new javax.swing.JLabel();
        Secciontxt1 = new javax.swing.JLabel();
        titulotipotxt2 = new javax.swing.JLabel();
        Siguientestxt1 = new javax.swing.JLabel();
        portadatxt1 = new javax.swing.JLabel();
        Siguientestxt2 = new javax.swing.JLabel();
        Secciontxt2 = new javax.swing.JLabel();
        tendrastxt2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Secciontxt = new javax.swing.JLabel();
        Siguientestxt = new javax.swing.JLabel();
        CrearEventoLabel = new javax.swing.JLabel();
        EliminarEventoLabel = new javax.swing.JLabel();
        ModificarEventoLabel = new javax.swing.JLabel();
        portadatxt = new javax.swing.JLabel();
        titulotipotxt1 = new javax.swing.JLabel();
        CrearEventoBoton = new javax.swing.JButton();
        ModificarEventoBoton = new javax.swing.JButton();
        EliminarEventoBoton = new javax.swing.JButton();
        FlechaIzquierdaBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tendrastxt.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        tendrastxt.setForeground(new java.awt.Color(255, 153, 204));
        tendrastxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendrastxt.setText("tendras que introducir las ");
        jPanel1.add(tendrastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 220, -1));

        tendrastxt1.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        tendrastxt1.setForeground(new java.awt.Color(255, 153, 204));
        tendrastxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendrastxt1.setText("pincha para dirigirte a la ventana");
        jPanel1.add(tendrastxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 230, -1));

        Secciontxt1.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        Secciontxt1.setForeground(new java.awt.Color(255, 153, 204));
        Secciontxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Secciontxt1.setText("Seccion para eliminar eventos");
        jPanel1.add(Secciontxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 30));

        titulotipotxt2.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        titulotipotxt2.setForeground(new java.awt.Color(255, 153, 204));
        titulotipotxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulotipotxt2.setText("titulo,tipo,direccion,precio,");
        jPanel1.add(titulotipotxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 210, 80));

        Siguientestxt1.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        Siguientestxt1.setForeground(new java.awt.Color(255, 153, 204));
        Siguientestxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Siguientestxt1.setText("y poder eliminar eventos");
        jPanel1.add(Siguientestxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 50));

        portadatxt1.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        portadatxt1.setForeground(new java.awt.Color(255, 153, 204));
        portadatxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portadatxt1.setText("portada y calificacion.");
        jPanel1.add(portadatxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 210, 50));

        Siguientestxt2.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        Siguientestxt2.setForeground(new java.awt.Color(255, 153, 204));
        Siguientestxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Siguientestxt2.setText("siguientes caracteristicas");
        jPanel1.add(Siguientestxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 220, 50));

        Secciontxt2.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        Secciontxt2.setForeground(new java.awt.Color(255, 153, 204));
        Secciontxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Secciontxt2.setText("Seccion para crear eventos en ella");
        jPanel1.add(Secciontxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 220, 30));

        tendrastxt2.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        tendrastxt2.setForeground(new java.awt.Color(255, 153, 204));
        tendrastxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendrastxt2.setText("tendras que introducir las ");
        jPanel1.add(tendrastxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 220, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 204));
        jLabel1.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("para modificar el evento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 170, -1));

        Secciontxt.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        Secciontxt.setForeground(new java.awt.Color(255, 153, 204));
        Secciontxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Secciontxt.setText("Seccion para modificar eventos");
        jPanel1.add(Secciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 230, 30));

        Siguientestxt.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        Siguientestxt.setForeground(new java.awt.Color(255, 153, 204));
        Siguientestxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Siguientestxt.setText("siguientes caracteristicas");
        jPanel1.add(Siguientestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 220, 50));

        CrearEventoLabel.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        CrearEventoLabel.setForeground(new java.awt.Color(255, 153, 204));
        CrearEventoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearEventoLabel.setText("CREAR EVENTO");
        jPanel1.add(CrearEventoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 220, 50));

        EliminarEventoLabel.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        EliminarEventoLabel.setForeground(new java.awt.Color(255, 153, 204));
        EliminarEventoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarEventoLabel.setText("ELIMINAR EVENTO");
        jPanel1.add(EliminarEventoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 50));

        ModificarEventoLabel.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        ModificarEventoLabel.setForeground(new java.awt.Color(255, 153, 204));
        ModificarEventoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ModificarEventoLabel.setText("MODIFICAR EVENTO");
        jPanel1.add(ModificarEventoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 210, 50));

        portadatxt.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        portadatxt.setForeground(new java.awt.Color(255, 153, 204));
        portadatxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portadatxt.setText("portada y calificacion.");
        jPanel1.add(portadatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 210, 50));

        titulotipotxt1.setFont(new java.awt.Font("Alef", 1, 12)); // NOI18N
        titulotipotxt1.setForeground(new java.awt.Color(255, 153, 204));
        titulotipotxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulotipotxt1.setText("titulo,tipo,direccion,precio,");
        jPanel1.add(titulotipotxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 220, 60));

        CrearEventoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (1).png"))); // NOI18N
        CrearEventoBoton.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(204, 0, 204)));
        CrearEventoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEventoBotonActionPerformed(evt);
            }
        });
        jPanel1.add(CrearEventoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 220, 400));

        ModificarEventoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crank (1).png"))); // NOI18N
        ModificarEventoBoton.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(204, 0, 204)));
        ModificarEventoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEventoBotonActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarEventoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 210, 400));

        EliminarEventoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minus (1).png"))); // NOI18N
        EliminarEventoBoton.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(204, 0, 204)));
        EliminarEventoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEventoBotonActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarEventoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 400));

        FlechaIzquierdaBoton.setBackground(new java.awt.Color(255, 153, 255));
        FlechaIzquierdaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow (1).png"))); // NOI18N
        FlechaIzquierdaBoton.setBorderPainted(false);
        FlechaIzquierdaBoton.setContentAreaFilled(false);
        FlechaIzquierdaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlechaIzquierdaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(FlechaIzquierdaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlechaIzquierdaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlechaIzquierdaBotonActionPerformed
        
        //Pasar a ventana de Administrador
        
        Administrador frame1 = new Administrador();
        frame1.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_FlechaIzquierdaBotonActionPerformed

    private void EliminarEventoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEventoBotonActionPerformed
        
        //Pasar a ventana EliminarEvento
        
        ConsultarEventos frame2 = new ConsultarEventos();
        frame2.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarEventoBotonActionPerformed

    private void CrearEventoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEventoBotonActionPerformed
        CrearEvento frame3 = new CrearEvento();
        frame3.setVisible(true);
        dispose();
    }//GEN-LAST:event_CrearEventoBotonActionPerformed

    private void ModificarEventoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEventoBotonActionPerformed
        ConsultarEventos frame4 = new ConsultarEventos();
        frame4.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModificarEventoBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearEventoBoton;
    private javax.swing.JLabel CrearEventoLabel;
    private javax.swing.JButton EliminarEventoBoton;
    private javax.swing.JLabel EliminarEventoLabel;
    private javax.swing.JButton FlechaIzquierdaBoton;
    private javax.swing.JButton ModificarEventoBoton;
    private javax.swing.JLabel ModificarEventoLabel;
    private javax.swing.JLabel Secciontxt;
    private javax.swing.JLabel Secciontxt1;
    private javax.swing.JLabel Secciontxt2;
    private javax.swing.JLabel Siguientestxt;
    private javax.swing.JLabel Siguientestxt1;
    private javax.swing.JLabel Siguientestxt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel portadatxt;
    private javax.swing.JLabel portadatxt1;
    private javax.swing.JLabel tendrastxt;
    private javax.swing.JLabel tendrastxt1;
    private javax.swing.JLabel tendrastxt2;
    private javax.swing.JLabel titulotipotxt1;
    private javax.swing.JLabel titulotipotxt2;
    // End of variables declaration//GEN-END:variables
}
