/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces.SesionAdmin;

import Clases.Eventos.Evento;
import Clases.GuardadoDatos.UtilJavaEventsEventos;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sergio
 */
public class ModificarEvento extends javax.swing.JFrame {
    private Evento eventoSelected;
    
    /**
     * Creates new form ModificarEvento
     */
    public ModificarEvento(Evento ev) {
        initComponents();
        this.eventoSelected = ev;
        cargarDatosTextField();
        
        
    }
    
    //Metodo que se encarga de colocar todos los datos de un evento que se han guardado en sus respectivas posiciones
    
    private void cargarDatosTextField() {
        TituloTxt.setText(eventoSelected.getTitulo());
        ComboBoxTipo.setSelectedItem(eventoSelected.getTipo());
        Calletxt.setText(eventoSelected.getDireccion().getCalle());
        NumeroTxt.setText(eventoSelected.getDireccion().getNumero());
        Codigopostaltxt.setText(eventoSelected.getDireccion().getCodigopostal());
        Ciudadtxt.setText(eventoSelected.getDireccion().getCiudad());
        Fechatxt.setText(eventoSelected.getFecha());
        Preciotxt.setText(eventoSelected.getPrecio());
        Horatxt.setText(eventoSelected.getHora());
        RutaImagen.setText(eventoSelected.getPortada());
        String rutaImagen = eventoSelected.getPortada();
        
        //Esta parte es la que se encarga de mostrar la imagen de nuevo otra vez al JLabel
        
        if (rutaImagen != null && !rutaImagen.isEmpty()) { //Esta linea se encarga de verificar que la variable rutaImagen no sea nula o este vacia
            ImageIcon iconoOriginal = new ImageIcon(rutaImagen); //En esta linea se crea una variable con la ruta de la imagen que hemos guardado cuando creamos el evento
            Image imagenOriginal = iconoOriginal.getImage(); //Obtiene la imagen de la imagen original por asi decirlo
            Image imagenEscalada = imagenOriginal.getScaledInstance(310, 250, Image.SCALE_SMOOTH); //Escala la imagen segun el tamaño del label al que quieres redireccionar la imagen en nuestro caso el label es 310x250
            ImageIcon iconoEscalado = new ImageIcon(imagenEscalada); //Convierte la imagen que hemos puesto en el label en una nueva variable y adapta el tamaño que hemos seleccionado antes.
            IconoImagen.setIcon(iconoEscalado); //Muestra la imagen en el JLable que en nuestro caso se llama IconoImagen y asi el usuario puede ver la imagen
            } else {
            IconoImagen.setIcon(null); // Si no hay ruta, se encargara de limpia el JLabel y dejarlo vacio.
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RutaImagen = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        CrearEventoLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        Tipo = new javax.swing.JLabel();
        TituloTxt = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        Direccion = new javax.swing.JLabel();
        Calletxt = new javax.swing.JTextField();
        Calle = new javax.swing.JLabel();
        EjCalle = new javax.swing.JLabel();
        NumeroTxt = new javax.swing.JTextField();
        Numero = new javax.swing.JLabel();
        EjNumero = new javax.swing.JLabel();
        Codigopostaltxt = new javax.swing.JTextField();
        CodigoPostal = new javax.swing.JLabel();
        EjCodigo = new javax.swing.JLabel();
        Ciudadtxt = new javax.swing.JTextField();
        Ciudad = new javax.swing.JLabel();
        EjCiudad = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        EjFecha = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        EjPrecio = new javax.swing.JLabel();
        Borrar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        IconoImagen = new javax.swing.JLabel();
        Horatxt = new javax.swing.JFormattedTextField();
        Hora = new javax.swing.JLabel();
        EjFecha1 = new javax.swing.JLabel();
        Fechatxt = new javax.swing.JFormattedTextField();
        Preciotxt = new javax.swing.JFormattedTextField();

        RutaImagen.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearEventoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CrearEventoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearEventoLabel.setText("MODIFICAR EVENTO");
        jPanel1.add(CrearEventoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 32));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 670, 10));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 20, 430));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 320, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 20));

        ComboBoxTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Deporte", "Concierto", "Académico", "Politico", "Cultural" }));
        jPanel1.add(ComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        Tipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tipo.setText("Tipo:");
        jPanel1.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 69, 40));

        TituloTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TituloTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TituloTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloTxtMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TituloTxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TituloTxtMouseReleased(evt);
            }
        });
        TituloTxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                TituloTxtComponentMoved(evt);
            }
        });
        TituloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloTxtActionPerformed(evt);
            }
        });
        jPanel1.add(TituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Titulo.setText("Titulo del Evento:");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 22));

        Imagen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Imagen.setText("Imagen:");
        jPanel1.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 69, 40));

        Agregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 80, -1));

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion.setText("DIRECCION");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 320, 50));

        Calletxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(Calletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, -1));

        Calle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Calle.setText("Calle:");
        jPanel1.add(Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, 40));

        EjCalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjCalle.setForeground(new java.awt.Color(153, 153, 153));
        EjCalle.setText("Ej:Bulevar Entrepeñas...");
        jPanel1.add(EjCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 120, 20));

        NumeroTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NumeroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroTxtActionPerformed(evt);
            }
        });
        jPanel1.add(NumeroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 110, -1));

        Numero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Numero.setText("Numero:");
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 70, 40));

        EjNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjNumero.setForeground(new java.awt.Color(153, 153, 153));
        EjNumero.setText("Ej: 8A, 4B, 2C...");
        jPanel1.add(EjNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 90, 20));

        Codigopostaltxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(Codigopostaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, -1));

        CodigoPostal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CodigoPostal.setText("Codigo Postal:");
        jPanel1.add(CodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 80, 20));

        EjCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjCodigo.setForeground(new java.awt.Color(153, 153, 153));
        EjCodigo.setText("Ej: 19005, 26007...");
        jPanel1.add(EjCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 100, 20));

        Ciudadtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(Ciudadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 110, -1));

        Ciudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ciudad.setText("Ciudad:");
        jPanel1.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 70, 30));

        EjCiudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjCiudad.setForeground(new java.awt.Color(153, 153, 153));
        EjCiudad.setText("Ej: Madrid, Vigo...");
        jPanel1.add(EjCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 100, 20));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Fecha.setText("Fecha:");
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 69, 22));

        EjFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjFecha.setForeground(new java.awt.Color(153, 153, 153));
        EjFecha.setText("dd/MM/yy");
        jPanel1.add(EjFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 120, 20));

        Precio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Precio.setText("Precio:");
        jPanel1.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 69, 30));

        EjPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjPrecio.setForeground(new java.awt.Color(153, 153, 153));
        EjPrecio.setText("Ej: 12,00€");
        jPanel1.add(EjPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 120, 20));

        Borrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Borrar.setText("Borrar");
        Borrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, 20));

        Regresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Regresar.setText("Regresar y guardar");
        Regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 120, 20));

        Volver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergio\\OneDrive\\Documentos\\NetBeansProjects\\JavaEvents\\src\\main\\resources\\left-arrow (1).png")); // NOI18N
        Volver.setBorderPainted(false);
        Volver.setContentAreaFilled(false);
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 40, 40));
        jPanel1.add(IconoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 310, 250));

        Horatxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jPanel1.add(Horatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 60, -1));

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Hora.setText("Hora");
        jPanel1.add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 110, 20));

        EjFecha1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EjFecha1.setForeground(new java.awt.Color(153, 153, 153));
        EjFecha1.setText("Ej:23:59");
        jPanel1.add(EjFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 50, 20));

        Fechatxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yy"))));
        jPanel1.add(Fechatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 90, -1));

        Preciotxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        jPanel1.add(Preciotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloTxtMouseClicked

    }//GEN-LAST:event_TituloTxtMouseClicked

    private void TituloTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloTxtMouseEntered

    }//GEN-LAST:event_TituloTxtMouseEntered

    private void TituloTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloTxtMousePressed

    }//GEN-LAST:event_TituloTxtMousePressed

    private void TituloTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloTxtMouseReleased
        
    }//GEN-LAST:event_TituloTxtMouseReleased

    private void TituloTxtComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TituloTxtComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloTxtComponentMoved

    private void TituloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloTxtActionPerformed

    }//GEN-LAST:event_TituloTxtActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        // Creamos un JFileChooser para poder seleccionar archivos
        JFileChooser fileChooser = new JFileChooser();
        /*
        Creamos un filtro a partir de un nuevo FileNameExtension donde solo vamos a poder mostrar archivos
        de tipo "jpg", "jpeg" y "png".
        Este filtro le establecemos en el jFileChooser para que solo se puedan seleccionar archivos con las
        extensiones indicadas
        */
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Imagen", "jpeg", "jpg", "png");
        fileChooser.setFileFilter(filtro);
        // La variable  selec la usamos para ver si el usuario seleccionó un archivo o
        int selec = fileChooser.showOpenDialog(this);
        // Si selecciona algún archivo
        if (selec == JFileChooser.APPROVE_OPTION) {
            String pathImagenEvento = fileChooser.getSelectedFile().getAbsolutePath(); // Obtenemos la ruta de la imagen
            // Creamos un ImageIcon y escalamos la imagen
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(pathImagenEvento).getImage().getScaledInstance(320, 260, Image.SCALE_DEFAULT));
            // La ponemos en el jLabel donde queremos que aparezca
            IconoImagen.setIcon(imageIcon);
            RutaImagen.setText(pathImagenEvento);

        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void NumeroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroTxtActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        
        //Vaciara todos los campos si presiona este boton
        
        TituloTxt.setText("");
        Calletxt.setText("");
        NumeroTxt.setText("");
        Codigopostaltxt.setText("");
        Ciudadtxt.setText("");
        Fechatxt.setText("");
        Preciotxt.setText("");
        ComboBoxTipo.setSelectedItem("Elegir");
    }//GEN-LAST:event_BorrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        
        //Guardara todos los datos de nuevo en el archivo de eventos.dat actualizando aquellos datos que se hayan modificado
        
        
        eventoSelected.setTitulo(TituloTxt.getText());
        eventoSelected.setTipo((String) ComboBoxTipo.getSelectedItem());
        eventoSelected.getDireccion().setCalle(Calletxt.getText());
        eventoSelected.getDireccion().setNumero(NumeroTxt.getText());
        eventoSelected.getDireccion().setCiudad(Ciudadtxt.getText());
        eventoSelected.getDireccion().setCodigopostal(Codigopostaltxt.getText());
        eventoSelected.setFecha(Fechatxt.getText());
        eventoSelected.setHora(Horatxt.getText());
        eventoSelected.setPrecio(Preciotxt.getText());
        // Guardar la ruta de la imagen seleccionada
        eventoSelected.setPortada(RutaImagen.getText());
        UtilJavaEventsEventos.guardarDatosEventos();
        JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.");
    }//GEN-LAST:event_RegresarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        UtilJavaEventsEventos.guardarDatosEventos();
        GestionEventos frame1 = new GestionEventos();
        frame1.setVisible(true); //Aparecer la pestaña
        dispose(); //Cerrar pestaña anterior
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Borrar;
    private javax.swing.JLabel Calle;
    private javax.swing.JTextField Calletxt;
    private javax.swing.JLabel Ciudad;
    private javax.swing.JTextField Ciudadtxt;
    private javax.swing.JLabel CodigoPostal;
    private javax.swing.JTextField Codigopostaltxt;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JLabel CrearEventoLabel;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel EjCalle;
    private javax.swing.JLabel EjCiudad;
    private javax.swing.JLabel EjCodigo;
    private javax.swing.JLabel EjFecha;
    private javax.swing.JLabel EjFecha1;
    private javax.swing.JLabel EjNumero;
    private javax.swing.JLabel EjPrecio;
    private javax.swing.JLabel Fecha;
    private javax.swing.JFormattedTextField Fechatxt;
    private javax.swing.JLabel Hora;
    private javax.swing.JFormattedTextField Horatxt;
    private javax.swing.JLabel IconoImagen;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Numero;
    private javax.swing.JTextField NumeroTxt;
    private javax.swing.JLabel Precio;
    private javax.swing.JFormattedTextField Preciotxt;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField RutaImagen;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField TituloTxt;
    private javax.swing.JButton Volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
